---
# tasks file for ansible-ocp-amq-streams
- name: "AMQ Streams :: Instala Operator"
  include_role:
    name: ocp-operator
  vars:
    debug_enabled: false
    operator_install_mode: helm
    operator_install_git_url: https://github.com/ansible-consulting-br/helm-operator.git
    operator_install_git_dest: /tmp/consulting-br/helm-operator/
    operator_install_folder: /tmp/consulting-br/output/
    operator_install_folder_subpath: operator/templates
    operator_install_helm_values_files: "{{ operator_install_helm_values_files }}"
    operator_install_helm_set_values: "{{ operator_install_helm_set_values }}"
    operator_install_namespace: "{{ amq_streams_install_namespace }}"

- name: "AMQ Streams :: Instala instância do Kafka"
  include_role:
    name: ocp-core
  vars:
    debug_enabled: false
    core_install_mode: helm
    core_install_git_url: https://github.com/ansible-consulting-br/helm-amq-streams.git
    core_install_git_dest: /tmp/consulting-br/helm-amq-streams/
    core_install_folder: /tmp/consulting-br/output/
    core_install_folder_subpath: helm-amq-streams/templates
    core_install_helm_values_files: "{{ amq_streams_install_helm_values_files }}"
    core_install_helm_set_values: "{{ amq_streams_install_helm_set_values }}"
    core_install_namespace: "{{ amq_streams_install_namespace }}"

- name: "AMQ Streams :: Aguarda status ready do Kafka"
  kubernetes.core.k8s_info:
    api_version: kafka.strimzi.io/v1beta2
    kind: Kafka
    name: "{{ amq_streams_install_name }}"
    namespace: "{{ amq_streams_install_namespace }}"
    wait: yes
    wait_sleep: 20
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: 'True'
  register: kafka_status_info